import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import axios from "axios";
import { event } from "../lib/gtag";
import { useEffect, useState } from "react";

export const getStaticProps = async () => {
  try {
    console.log(process.env.NEXT_PUBLIC_GA_ID);
    let res = await axios.get(`http://localhost:5000/products`);

    return {
      // data dimasukkan kedalam props
      props: {
        products: res.data,
      },
      // revalidate digunakan untuk server fetching uldang dan generate html baru
      // tiap sepuluh detik setelah request pertama
      revalidate: 10,
    };
  } catch (error) {
    return {
      props: {
        products: [],
        error_message: "server error bro",
      },
    };
  }
};

const addToCart = (productName) => {
  event({
    action: "add_to_cart",
    category: "ecommerce",
    label: "add-cart",
    value: productName,
  });
  alert("berhasil add to cart");
};

export default function Home(props) {
  // let x = localStorage.getItem("waktu");
  // if (!localStorage.getItem("waktu")) {
  //   x = 10;
  // }
  let [time, settime] = useState(10);

  useEffect(() => {
    // let timeinit = 10;
    if (time <= 0) {
      clearInterval(timer);
      return;
    }
    if (!localStorage.getItem("waktu") || localStorage.getItem("waktu") == 0) {
      localStorage.setItem("waktu", 10);
      settime(10);
    } else {
      let res = localStorage.getItem("waktu");
      settime(res);
    }
    let timer = setInterval(() => {
      console.log(time);
      settime(time - 1);
      localStorage.setItem("waktu", time - 1);
    }, 1000);
    return () => {
      clearInterval(timer);
    };
  }, [time]);

  return (
    <div className={styles.container}>
      <Head>
        <title>dino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {props.products.map((val, index) => {
          return (
            <h5
              onClick={() => addToCart(val.name)}
              key={index}
              className="text-lg"
            >
              {val.name}
            </h5>
          );
        })}
        <h1 className={styles.title}>
          Welcome to {time} <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href="/login">
          <a>login</a>
        </Link>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
